### ISSUE TITLE
Nachrichten direkt auch an einen Chat senden

### ISSUE THREAD

**Issue by chrischivlog** [ifheroes/infinityheroes-bot#2]
Hey Luca, 

wie bereits vor kurzem mal auf Discord angekündigt hätten wir gerne eine weitere Funktion des Bots. Der Bot soll wenn wir Nachrichten versenden über den Befehl nicht nur eine JSON-Datei mit der Nachricht anlegen sondern diese auch direkt in den Discord posten. Am besten in den Kanal, in dem man sich gerade befindet.

Die Funktion hat keine Eile ;)

**Comment by EckigerLuca** [comment]
Okay, ist eigentlich nur eine Zeile im Code ändern, ich schließe das Issue wenn ich fertig bin ^^

**Comment by EckigerLuca** [comment]
Feature wurde umgesetzt, siehe [hier](https://github.com/ifheroes/discord-website-bot-js/commit/8b0e30883b510f7b70b9527393355608c867e09a)
