### ISSUE TITLE
Formatierung im Chat

### ISSUE THREAD

**Issue by chrischivlog** [ifheroes/infinityheroes-bot#4]
Hey, 
wäre cool wenn man mit dem Bot auch Zeilenumbrüche in der Nachricht darstellen könnte. Wäre das möglich?

Ebenfalls wäre es cool wenn man aktivieren könnte das man alle, also @everyone anpingen kann.

Grüße Chris :)

**Comment by FrauJulian** [comment]
Hallo @chrischivlog!

Dieses Issue ist bereits länger offen. Ich würde das ggf. übernehmen. 
Auf welches Feature ist das hier bezogen? - Auf das hier? https://github.com/ifheroes/infinityheroes-bot/blob/main/src/commands/post/newpost.js

LG Julian

**Comment by chrischivlog** [comment]
Hey @FrauJulian 

sehr gerne würde mich freuen. Genau das Feature bezieht sich auf den gezeigten Code. @EckigerLuca kann aber eventuell nochmal hier darunter Kommentieren ob das korrekt ist. 

Feel free to fork ;)

**Comment by FrauJulian** [comment]
Servas @chrischivlog!

Der Pull Request #9 ist offen ^^

LG

**Comment by EckigerLuca** [comment]
Fixed with commit ddfd03cb13f5c3e1d5a3806cbd67e3c8502da8be
