### ISSUE TITLE
Add Base64 Image to JSON

### ISSUE THREAD

**Issue by chrischivlog** [ifheroes/infinityheroes-bot#8]
#### Current Situation  
Currently, images are uploaded to a file server and referenced in the JSON export through a URL link. Here's an example of the current structure:  

```json
{
  "title": "Es geht weiter...",
  "text": "Hey! Unser frisch veröffentlichter Server-Lead für das zweite Quartal ist da. Freut euch auf eine Fülle an technischen Verbesserungen, brandneuen Features und spannenden Events. 🛠️ Wir sind gespannt auf euer Feedback, denn eure Meinungen und Vorschläge sind uns ungemein wichtig! 💬 Gemeinsam gestalten wir die Zukunft unseres Minecraft-Servers. Lasst uns diese Reise gemeinsam fortsetzen. 🌍 Vielen Dank für euren Support in den vergangenen Monaten! 🙌 \n https://wiki.ifheroes.de/books/roadmap/page/lead-apr-jun-2024",
  "image": "https://data.ifheroes.de/apps/files_sharing/publicpreview/eMXpL6mMPomoNp2?file=/&fileId=2464&x=2560&y=1440&a=true&etag=d39a2309f80c7be38b2017d271c9af79"
}
```  

While functional, this approach introduces a dependency on the file server. If the file server is offline or URLs change, the images cannot be accessed, potentially breaking the functionality or appearance of exported content.

---

#### Proposed Solution  
To improve the resilience of the exported data, we propose enhancing the JSON export to include an additional Base64-encoded representation of the image. This allows the image to be displayed even if the file server is unavailable. The new structure would look like this:  

```json
{
  "title": "Es geht weiter...",
  "text": "Hey! Unser frisch veröffentlichter Server-Lead für das zweite Quartal ist da. Freut euch auf eine Fülle an technischen Verbesserungen, brandneuen Features und spannenden Events. 🛠️ Wir sind gespannt auf euer Feedback, denn eure Meinungen und Vorschläge sind uns ungemein wichtig! 💬 Gemeinsam gestalten wir die Zukunft unseres Minecraft-Servers. Lasst uns diese Reise gemeinsam fortsetzen. 🌍 Vielen Dank für euren Support in den vergangenen Monaten! 🙌 \n https://wiki.ifheroes.de/books/roadmap/page/lead-apr-jun-2024",
  "image": {
    "mime": "image/webp",
    "data": "UklGRhLVAQBXRUJQVlA4IAbVAQDwFQudASqpBoYDPm0ylUckIycqJ3N7mUANiWNsz5tf71297sDf0po3GYpz9E9U3g+u6v...."
  }
}
```  

---

#### Benefits  
1. **Offline Accessibility**: Ensures images are always accessible, regardless of the availability of the file server.  
2. **Resilience to URL Changes**: Prevents issues caused by broken or updated URLs.  
3. **Improved User Experience**: Enhances reliability for users consuming the exported data.  

---

#### Implementation Plan  
1. Modify the export functionality to:  
   - Download the image from the provided URL during export.  
   - Encode the image in Base64 format.  
   - Include the encoded data in the JSON export under an `image` object with `mime` and `data` fields.  
2. Add documentation and tests to validate the new functionality.  

---  

#### Additional Notes  
This enhancement supports the overall goal of improving the accessibility and reliability of our website. It safeguards against server issues or link changes, providing a more robust data export process.

**Comment by FrauJulian** [comment]
Wie genau ist der Plan für das?

Ich verstehe nicht so ganz um was es geht. ^^

**Comment by chrischivlog** [comment]
> Wie genau ist der Plan für das?
> 
> 
> 
> Ich verstehe nicht so ganz um was es geht. ^^

Würde mich hier nochmal im laufe der Woche melden. Das Feature ist aktuell nur im Internen Backlog unseres Teams. 

Sorry dafür. Ich ergänze, das dann noch im Issue. :)

**Comment by FrauJulian** [comment]
Ich kann und werde das probably die Tage mal machen. Schaut recht easy aus.

Wenn ihr wollt könnt ihr das mir assignen wenn das überhaupt geht ^^

LG

**Comment by FrauJulian** [comment]
PR #11 Fixed
